version: '3.8'

services:
  server:
    depends_on:
      - mysqldb
      - mongodb
      - redis
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $SERVER_LOCAL_PORT:$SERVER_DOCKER_PORT
    environment:
      - MYSQL_DB_HOST=mysqldb
      - MYSQL_DB_USER=$MYSQLDB_USER
      - MYSQL_DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DB_NAME=$MYSQLDB_DATABASE
      - MYSQL_DB_PORT=$MYSQLDB_DOCKER_PORT
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_USER=$MONGO_USER
      - MONGO_DB_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_DB_NAME=$MONGO_DATABASE
      - MONGO_DB_PORT=$MONGO_DOCKER_PORT
    stdin_open: true
    tty: true
  mysqldb:
    image: mysql:8.0.34
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql_db:/var/lib/mysql
  mongodb:
    image: mongo:7.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
    volumes:
      - mongo_db:/data/db
  redis:
    image: "redis:7.2.1-alpine3.18"
    ports:
      - 6379:6379

volumes:
  mysql_db:
  mongo_db: